### ISSUE TITLE
OpenXR and other VR platforms

### ISSUE THREAD

**Issue by dhsavell** [dhsavell/raylib-openvr#2]
I wanted to make this issue as a note that I'm not against exploring OpenXR over OpenVR for this project, since OpenXR seems like the future. I tried to get raylib and OpenXR working in the same project, but unfortunately ran into problem after problem including `Windows.h` (and pre-existing `#define` tricks didn't seem to work). Maybe I'll explore it again when I have more time.

What this means today is that the API has to be flexible enough to support either backend. On the developer end, this will look like a `#define` before importing raylib.

For now, I'm going to focus on developing good, working OpenVR support first. After achieving that basis, it should be easier to design the API.

Update: Totally forgot about WebXR as well. That would be fun to support. See https://www.w3.org/TR/webxr/, https://github.com/VhiteRabbit/emscripten-webxr.

**Comment by TiagoSilvaPereira** [comment]
Hi @branchpanic did you had any success in integrating openxr with raylib?

**Comment by branchpanic** [comment]
It never really ended up happening. The notes above summarize all the progress that was made. Let me know if you have any questions about it though.

**Comment by TiagoSilvaPereira** [comment]
@branchpanic thank you for your answer... I'm thinking of creating a simple engine for VR, but taking advantage of an existing rendering framework, and I liked Raylib's proposal. I'll see if I can do something
